version: '3'

services:
  master:
    image: mysql/mysql-server:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    container_name: 'master'
    restart: unless-stopped
    ports:
      - "3309:3306"
    volumes:
      - ./master/conf/mysql.conf.cnf:/etc/my.cnf
      - ./master/data:/var/lib/mysql

  slave:
    image: mysql/mysql-server:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    container_name: 'slave'
    ports:
      - "3310:3306"
    depends_on:
      - master
    restart: unless-stopped
    volumes:
      - ./slave/conf/mysql.conf.cnf:/etc/my.cnf
      - ./slave/data:/var/lib/mysql