version: '3'

services:
  mysql-master:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=It235711
    container_name: 'mysql_master'
    restart: "no"
    ports:
      - "3307:3306"
    volumes:
      - ./master/conf.d:/etc/mysql/mysql.conf.d/
      - ./master/data:/var/lib/mysql
    networks:
      - overlay

  mysql-slave:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=It235711
    container_name: 'mysql_slave'
    ports:
      - "3308:3306"
    depends_on:
      - mysql-master
    restart: "no"
    volumes:
      - ./slave/conf.d:/etc/mysql/mysql.conf.d/
      - ./slave/data:/var/lib/mysql
    networks:
      - overlay

networks:
  overlay: